_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: 60ab2b3b-c9c5-48ff-8fc2-a9d34b5c8c21
name: circleci-buildtools
mail: nathan.plowman@ffwagency.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
